### PR TITLE
introduce dm_has_type judgment and move "cons" part of D_Mem/D_Fun into D_Cons

### PR DESCRIPTION
**Pull request by samuelgruetter**
Allows proofs to treat the "cons" aspect and induction separately from the D_Mem/D_Fun typechecking.
And having a dm_has_type judgment is useful for proofs about typechecking algorithms.
Review by @namin please

### CODE REVIEW

**Comment by TiarkRompf** [comment]
Why not just use Coq's `list' data type?

**Comment by samuelgruetter** [comment]
@TiarkRompf because I don't know how to make structural recursion (needed eg in open and subst) work if we use `list dm` instead of our own `dms`: If I define the opening as follows

```
...(same as before)...
with dms_open (k: nat) (u: vr) (ds: list dm) { struct ds }: dms :=
   match ds with
     | [] => []
     | d :: rest => (dm_open k u d) :: (dms_open k u rest)
   end.
```

Coq says `Recursive call to dm_open has principal argument equal to "d" instead of "rest".`

Do you know how to make this work?

**Comment by TiarkRompf** [comment]
I think it should work if you define `dms_open` inside `dm_open`

**Comment by TiarkRompf** [comment]
Maybe you can even use map?

**Comment by samuelgruetter** [comment]
Yes, `map` seems to work indeed:

```
Fixpoint vr_open (k: nat) (u: vr) (v: vr) { struct v }: vr :=
  match v with
    | VarF x => VarF x
    | VarB x => if beq_nat k x then u else VarB x
    | VObj ds => VObj (map (dm_open (S k) u) ds)
  end
...(same as before but no dms_open)...
```

It works because the definition of `map` is transparent. Before, when we were using LibTLC, which defines its own non-transparent `map`, this did not work, so that's why I did not even dare to try out `map` ;-)

**Comment by namin** [comment]
👍

**Comment by samuelgruetter** [comment]
Ok so I tried to define `dms` as an alias for `list dm`, see [this commit](https://github.com/TiarkRompf/minidot/commit/c1e0b6aa9fc2421395f5040412afdc6ebda655a0).
It looks all nice _except_ that we cannot automatically create a combined induction scheme over the syntax (vr/ty/tm/dm), and this is quite serious (we need such induction for all lemmas about open and subst). In some cases we can use the `closed_mutind` scheme instead, but only if we have such a hypothesis.

If I try to define

```
Scheme vr_mut := Induction for vr Sort Prop
with   ty_mut := Induction for ty Sort Prop
with   tm_mut := Induction for tm Sort Prop
with   dm_mut := Induction for dm Sort Prop.
Combined Scheme syntax_mutind from vr_mut, ty_mut, tm_mut, dm_mut.
```

Coq (8.4pl6 as well as 8.5) produces the following error:

```
Error: Illegal application (Type Error): 
The term "f" of type "forall i : id, P (VarF i)"
cannot be applied to the term
 "TBot" : "ty"
This term has type "ty" which should be coercible to "id".
```

Which I read as "sorry, what you're trying to do here is too advanced for me" (I've seen various non-sensical errors when creating combined induction schemes before, this seems to be common...).

Does anyone have an idea how to obtain such an induction scheme?
It's not the first time I fail at this problem ;-)

**Comment by namin** [comment]
:) I suspected this would show up.

In any case, please merge this commit as it is, as it improves things already.

**Comment by namin** [comment]
https://coq.inria.fr/cocorico/Mutual%20Induction

**Comment by TiarkRompf** [comment]
You can define a custom induction scheme for `list dm` (using `Fixpoint`), and include it in the call to `Scheme`. There's a chapter in the Coq'Art book that shows how it's done.

**Comment by namin** [comment]
Apart from the Coq-fu fun, I'd rather stick with standard scheme and custom list than the other way :)

**Comment by samuelgruetter** [comment]
Yes, custom lists are much simpler than custom induction schemes... I have some [bad memories](https://github.com/samuelgruetter/dot-calculus/commit/5c3c579) about them: They tend to be big brittle hard to maintain boilerplate constructs.

**Comment by samuelgruetter** [comment]
Btw a good example of this can be found in the [Coq development](http://www.ii.uni.wroc.pl/~dabi/publications/Haskell10/stg-in-coq/stg-in-coq.tar.gz) accompanying the paper [A Systematic Derivation of the STG Machine Verified in Coq](http://www.ii.uni.wroc.pl/~dabi/publications/index.html) by Maciej Piróg and Dariusz Biernacki.
But I'm not goint to try it out now ;-)

**Pull request merged**
